local blankline = {
   indentLine_enabled = 1,
   filetype_exclude = {
      "help",
      "terminal",
      "alpha",
      "lazy",
      "lspinfo",
      "TelescopePrompt",
      "TelescopeResults",
      "mason",
      "nvdash",
      "nvcheatsheet",
      "",
   },
   char = "▏",
   buftype_exclude = { "terminal" },
   show_trailing_blankline_indent = false,
   show_current_context = true,
   show_current_context_start = true,
}
